// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJeeqJ-IhW09I7Ub-sExoRem3OBuEMf0o',
    appId: '1:490287516673:web:eb6ff12d5f7323c43c8400',
    messagingSenderId: '490287516673',
    projectId: 'todoapp-383f5',
    authDomain: 'todoapp-383f5.firebaseapp.com',
    storageBucket: 'todoapp-383f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEe18K1dA9xR1ZhKRWrLQta-fU6sgS5CE',
    appId: '1:490287516673:android:e6677d0caa3982c13c8400',
    messagingSenderId: '490287516673',
    projectId: 'todoapp-383f5',
    storageBucket: 'todoapp-383f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYXsEHObF8uFnBgaWmHrVJfjqnGWJdis',
    appId: '1:490287516673:ios:59b9723ea8b206b53c8400',
    messagingSenderId: '490287516673',
    projectId: 'todoapp-383f5',
    storageBucket: 'todoapp-383f5.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJYXsEHObF8uFnBgaWmHrVJfjqnGWJdis',
    appId: '1:490287516673:ios:59b9723ea8b206b53c8400',
    messagingSenderId: '490287516673',
    projectId: 'todoapp-383f5',
    storageBucket: 'todoapp-383f5.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJeeqJ-IhW09I7Ub-sExoRem3OBuEMf0o',
    appId: '1:490287516673:web:6ce8c67ba9466c9c3c8400',
    messagingSenderId: '490287516673',
    projectId: 'todoapp-383f5',
    authDomain: 'todoapp-383f5.firebaseapp.com',
    storageBucket: 'todoapp-383f5.firebasestorage.app',
  );
}
